#
# This file is part of TEN Framework, an open source project.
# Licensed under the Apache License, Version 2.0.
# See the LICENSE file for more information.
#
from pydantic import BaseModel
from enum import IntEnum


class TurnStatus(IntEnum):
    IN_PROGRESS = 0
    END = 1  # End gracefully
    INTERRUPTED = 2  # End by interrupt


class Word(BaseModel):
    word: str = ""
    start_ms: int = 0  # start time of the word, milliseconds since epoch
    duration_ms: int = 0  # duration of the word, in milliseconds
    stable: bool = True  # whether 'word' won't change anymore


class UserTranscription(BaseModel):
    object: str = "user.transcription"  # [required] name of the object
    text: str = ""  # [required] text for display
    final: bool = True  # whether 'text' won't change anymore
    start_ms: int = 0  # start time of the text, milliseconds since epoch
    duration_ms: int = 0  # duration of the text, in milliseconds
    language: str = ""  # IETF BCP 47(RFC 4646), such as 'en-US' or 'zh-CN'

    turn_id: int = 0

    # which stream/user the text belongs to
    stream_id: int = 0
    user_id: str = ""

    words: list[Word] | None = None
    merged_turns: list[int] | None = None    # TODO: should be removed in the future
    interruptable: bool = False  # whether the text can be interrupted

    metadata: dict | None = None  # additional metadata for the transcription

class UserTranslation(BaseModel):
    object: str = "user.translation"  # [required] name of the object
    text: str = ""  # [required] text for display
    final: bool = True  # whether 'text' won't change anymore
    start_ms: int = 0  # start time of the text, milliseconds since epoch
    duration_ms: int = 0  # duration of the text, in milliseconds
    language: str = ""  # IETF BCP 47(RFC 4646), such as 'en-US' or 'zh-CN'

    turn_id: int = 0

    # which stream/user the text belongs to
    stream_id: int = 0
    user_id: str = ""

    transcript_text: str | None = None  # corresponding transcribed text
    transcript_language: str | None = None  # IETF BCP 47(RFC 4646), such as 'en-US' or 'zh-CN'

    metadata: dict | None = None  # additional metadata for the transcription


class AssistantTranscription(BaseModel):
    object: str = "assistant.transcription"  # [required] name of the object
    text: str = ""  # [required] text for display
    start_ms: int = 0  # start time of the text, milliseconds since epoch
    duration_ms: int = 0  # duration of the text, in milliseconds
    language: str = ""  # IETF BCP 47(RFC 4646), such as 'en-US' or 'zh-CN'

    quiet: bool = False  # expect to pronounce or not
    reasoning: bool = False  # whether the text is generated by reasoning

    turn_id: int = 0
    turn_seq_id: int = 0

    # 0: in-progress, 1: end gracefully, 2: interrupted, otherwise undefined
    turn_status: int = 0
    source: str = ""

    # which stream/user the text belongs to
    stream_id: int = 0
    user_id: str = ""

    words: list[Word] | None = None
    interruptable: bool = False  # whether the text can be interrupted

    metadata: dict | None = None  # additional metadata for the transcription
